version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bookstore_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookstore
      MYSQL_USER: bookstoreuser
      MYSQL_PASSWORD: bookstorepassword
    ports:
      - "3307:3306"  
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: